-- Campus Connect — PostgreSQL schema for Supabase
-- Powered by LAVIDA
-- Generated 2026-10-07 from Django migrations
--
-- HOW TO USE (Supabase):
--   1. Supabase dashboard -> SQL Editor -> New query
--   2. Paste this whole file and Run. It creates every table, index,
--      constraint and the Django bookkeeping tables.
--   3. Then point the app at the same database and run
--      'python manage.py migrate --fake-initial' so Django records these
--      migrations as applied, followed by 'python manage.py savana_setup'.
--
-- NOTE: Prefer running 'python manage.py migrate' directly against
--       Supabase (identical result, less copy/paste). This file is for
--       teams that want to review or apply the raw DDL themselves.

BEGIN;

--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name";
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
--
-- Alter field email on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field last_login on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field last_name on user
--
-- (no-op)
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field first_name on user
--
-- (no-op)
--
-- Create model User
--
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "phone" varchar(32) NOT NULL, "is_customer" boolean NOT NULL, "age_verified" boolean NOT NULL, "date_of_birth" date NULL);
CREATE TABLE "accounts_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "accounts_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model CustomerProfile
--
CREATE TABLE "accounts_customerprofile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "full_name" varchar(160) NOT NULL, "phone" varchar(32) NOT NULL, "declarations" jsonb NOT NULL, "marketing_opt_in" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL UNIQUE);
--
-- Create model Address
--
CREATE TABLE "accounts_address" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(12) NOT NULL, "label" varchar(80) NOT NULL, "recipient" varchar(160) NOT NULL, "phone" varchar(32) NOT NULL, "line1" varchar(200) NOT NULL, "line2" varchar(200) NOT NULL, "city" varchar(120) NOT NULL, "area" varchar(120) NOT NULL, "notes" varchar(255) NOT NULL, "is_default" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "customer_id" bigint NOT NULL);
CREATE INDEX "accounts_user_username_6088629e_like" ON "accounts_user" ("username" varchar_pattern_ops);
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
ALTER TABLE "accounts_customerprofile" ADD CONSTRAINT "accounts_customerprofile_user_id_56cc9af8_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_address" ADD CONSTRAINT "accounts_address_customer_id_224ca293_fk_accounts_user_id" FOREIGN KEY ("customer_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_address_customer_id_224ca293" ON "accounts_address" ("customer_id");
CREATE INDEX "accounts_ad_custome_8fdba3_idx" ON "accounts_address" ("customer_id", "kind");
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
--
-- Alter field action_time on logentry
--
-- (no-op)
--
-- Alter field action_flag on logentry
--
-- (no-op)
--
-- Create model Category
--
CREATE TABLE "catalog_category" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "slug" varchar(140) NOT NULL UNIQUE, "description" text NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0), "is_active" boolean NOT NULL);
--
-- Create model Product
--
CREATE TABLE "catalog_product" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "slug" varchar(220) NOT NULL UNIQUE, "sku" varchar(64) NOT NULL UNIQUE, "short_description" varchar(255) NOT NULL, "description" text NOT NULL, "price" numeric(12, 2) NOT NULL, "sale_price" numeric(12, 2) NULL, "currency" varchar(8) NOT NULL, "stock_quantity" integer NOT NULL CHECK ("stock_quantity" >= 0), "low_stock_threshold" integer NOT NULL CHECK ("low_stock_threshold" >= 0), "status" varchar(16) NOT NULL, "is_featured" boolean NOT NULL, "specifications" jsonb NOT NULL, "extra_information" text NOT NULL, "warnings" text NOT NULL, "age_restriction" integer NULL CHECK ("age_restriction" >= 0), "regulatory_classification" varchar(20) NOT NULL, "compliance_information" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "category_id" bigint NOT NULL);
--
-- Create model InventoryMovement
--
CREATE TABLE "catalog_inventorymovement" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "reason" varchar(16) NOT NULL, "quantity_delta" integer NOT NULL, "resulting_quantity" integer NOT NULL CHECK ("resulting_quantity" >= 0), "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "created_by_id" bigint NULL, "product_id" bigint NOT NULL);
--
-- Create model ComplianceRecord
--
CREATE TABLE "catalog_compliancerecord" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(12) NOT NULL, "age_verification_required" boolean NOT NULL, "required_declarations" jsonb NOT NULL, "merchant_license_info" text NOT NULL, "geographic_restrictions" varchar(255) NOT NULL, "product_restrictions" text NOT NULL, "required_warnings" text NOT NULL, "approved_at" timestamp with time zone NULL, "notes" text NOT NULL, "updated_at" timestamp with time zone NOT NULL, "approved_by_id" bigint NULL, "product_id" bigint NOT NULL UNIQUE);
--
-- Create model ProductImage
--
CREATE TABLE "catalog_productimage" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image" varchar(100) NULL, "external_url" varchar(200) NOT NULL, "alt_text" varchar(200) NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0), "product_id" bigint NOT NULL);
--
-- Create index catalog_pro_status_521020_idx on field(s) status of model product
--
CREATE INDEX "catalog_pro_status_521020_idx" ON "catalog_product" ("status");
--
-- Create index catalog_pro_categor_da0f0a_idx on field(s) category, status of model product
--
CREATE INDEX "catalog_pro_categor_da0f0a_idx" ON "catalog_product" ("category_id", "status");
--
-- Create index catalog_pro_slug_2b1eb6_idx on field(s) slug of model product
--
CREATE INDEX "catalog_pro_slug_2b1eb6_idx" ON "catalog_product" ("slug");
--
-- Create index catalog_inv_product_3dd629_idx on field(s) product, created_at of model inventorymovement
--
CREATE INDEX "catalog_inv_product_3dd629_idx" ON "catalog_inventorymovement" ("product_id", "created_at");
CREATE INDEX "catalog_category_name_fdc3466c_like" ON "catalog_category" ("name" varchar_pattern_ops);
CREATE INDEX "catalog_category_slug_dbf63ad0_like" ON "catalog_category" ("slug" varchar_pattern_ops);
ALTER TABLE "catalog_product" ADD CONSTRAINT "catalog_product_category_id_35bf920b_fk_catalog_category_id" FOREIGN KEY ("category_id") REFERENCES "catalog_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "catalog_product_slug_f37848b0_like" ON "catalog_product" ("slug" varchar_pattern_ops);
CREATE INDEX "catalog_product_sku_5c54c070_like" ON "catalog_product" ("sku" varchar_pattern_ops);
CREATE INDEX "catalog_product_category_id_35bf920b" ON "catalog_product" ("category_id");
ALTER TABLE "catalog_inventorymovement" ADD CONSTRAINT "catalog_inventorymov_created_by_id_51d24263_fk_accounts_" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "catalog_inventorymovement" ADD CONSTRAINT "catalog_inventorymov_product_id_6a70d4ef_fk_catalog_p" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "catalog_inventorymovement_created_by_id_51d24263" ON "catalog_inventorymovement" ("created_by_id");
CREATE INDEX "catalog_inventorymovement_product_id_6a70d4ef" ON "catalog_inventorymovement" ("product_id");
ALTER TABLE "catalog_compliancerecord" ADD CONSTRAINT "catalog_compliancere_approved_by_id_357d7258_fk_accounts_" FOREIGN KEY ("approved_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "catalog_compliancerecord" ADD CONSTRAINT "catalog_compliancere_product_id_3faa5cbd_fk_catalog_p" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "catalog_compliancerecord_approved_by_id_357d7258" ON "catalog_compliancerecord" ("approved_by_id");
ALTER TABLE "catalog_productimage" ADD CONSTRAINT "catalog_productimage_product_id_1f42dd8c_fk_catalog_product_id" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "catalog_productimage_product_id_1f42dd8c" ON "catalog_productimage" ("product_id");
--
-- Create model FulfilmentMethod
--
CREATE TABLE "store_fulfilmentmethod" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "kind" varchar(12) NOT NULL, "is_active" boolean NOT NULL, "fee" numeric(10, 2) NOT NULL, "delivery_areas" text NOT NULL, "instructions" text NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model NotificationTemplate
--
CREATE TABLE "store_notificationtemplate" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event" varchar(60) NOT NULL UNIQUE, "subject" varchar(200) NOT NULL, "body" text NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model PaymentMethod
--
CREATE TABLE "store_paymentmethod" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "slug" varchar(140) NOT NULL UNIQUE, "is_active" boolean NOT NULL, "instructions" text NOT NULL, "account_name" varchar(160) NOT NULL, "account_number" varchar(120) NOT NULL, "reference_hint" varchar(200) NOT NULL, "requires_proof" boolean NOT NULL, "sort_order" integer NOT NULL CHECK ("sort_order" >= 0));
--
-- Create model PickupLocation
--
CREATE TABLE "store_pickuplocation" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(160) NOT NULL, "address" varchar(255) NOT NULL, "hours" varchar(160) NOT NULL, "instructions" text NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model StoreSetting
--
CREATE TABLE "store_storesetting" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "key" varchar(100) NOT NULL UNIQUE, "value" jsonb NOT NULL, "group" varchar(40) NOT NULL, "label" varchar(160) NOT NULL);
--
-- Create model AnalyticsEvent
--
CREATE TABLE "store_analyticsevent" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(60) NOT NULL, "properties" jsonb NOT NULL, "session_key" varchar(64) NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model MerchantProfile
--
CREATE TABLE "store_merchantprofile" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "contact_name" varchar(160) NOT NULL, "contact_email" varchar(254) NOT NULL, "contact_phone" varchar(40) NOT NULL, "license_info" text NOT NULL, "operating_info" text NOT NULL, "is_active" boolean NOT NULL);
CREATE TABLE "store_merchantprofile_fulfilment_methods" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "merchantprofile_id" bigint NOT NULL, "fulfilmentmethod_id" bigint NOT NULL);
CREATE TABLE "store_merchantprofile_supported_categories" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "merchantprofile_id" bigint NOT NULL, "category_id" bigint NOT NULL);
CREATE TABLE "store_merchantprofile_payment_methods" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "merchantprofile_id" bigint NOT NULL, "paymentmethod_id" bigint NOT NULL);
CREATE TABLE "store_merchantprofile_pickup_locations" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "merchantprofile_id" bigint NOT NULL, "pickuplocation_id" bigint NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "store_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(80) NOT NULL, "object_type" varchar(80) NOT NULL, "object_id" varchar(80) NOT NULL, "metadata" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NULL);
--
-- Create model Notification
--
CREATE TABLE "store_notification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event" varchar(60) NOT NULL, "subject" varchar(200) NOT NULL, "body" text NOT NULL, "order_number" varchar(40) NOT NULL, "is_read" boolean NOT NULL, "provider" varchar(40) NOT NULL, "created_at" timestamp with time zone NOT NULL, "recipient_id" bigint NULL);
CREATE INDEX "store_notificationtemplate_event_9849dec1_like" ON "store_notificationtemplate" ("event" varchar_pattern_ops);
CREATE INDEX "store_paymentmethod_slug_b8b0f4a5_like" ON "store_paymentmethod" ("slug" varchar_pattern_ops);
CREATE INDEX "store_storesetting_key_8eb60fd3_like" ON "store_storesetting" ("key" varchar_pattern_ops);
CREATE INDEX "store_analy_name_1f43a5_idx" ON "store_analyticsevent" ("name", "created_at");
ALTER TABLE "store_merchantprofile_fulfilment_methods" ADD CONSTRAINT "store_merchantprofile_fu_merchantprofile_id_fulfi_e3696f1d_uniq" UNIQUE ("merchantprofile_id", "fulfilmentmethod_id");
ALTER TABLE "store_merchantprofile_fulfilment_methods" ADD CONSTRAINT "store_merchantprofil_merchantprofile_id_4ea27458_fk_store_mer" FOREIGN KEY ("merchantprofile_id") REFERENCES "store_merchantprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_merchantprofile_fulfilment_methods" ADD CONSTRAINT "store_merchantprofil_fulfilmentmethod_id_24a867fb_fk_store_ful" FOREIGN KEY ("fulfilmentmethod_id") REFERENCES "store_fulfilmentmethod" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_merchantprofile_fulf_merchantprofile_id_4ea27458" ON "store_merchantprofile_fulfilment_methods" ("merchantprofile_id");
CREATE INDEX "store_merchantprofile_fulf_fulfilmentmethod_id_24a867fb" ON "store_merchantprofile_fulfilment_methods" ("fulfilmentmethod_id");
ALTER TABLE "store_merchantprofile_supported_categories" ADD CONSTRAINT "store_merchantprofile_su_merchantprofile_id_categ_c210c18d_uniq" UNIQUE ("merchantprofile_id", "category_id");
ALTER TABLE "store_merchantprofile_supported_categories" ADD CONSTRAINT "store_merchantprofil_merchantprofile_id_deab69be_fk_store_mer" FOREIGN KEY ("merchantprofile_id") REFERENCES "store_merchantprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_merchantprofile_supported_categories" ADD CONSTRAINT "store_merchantprofil_category_id_b16b4dba_fk_catalog_c" FOREIGN KEY ("category_id") REFERENCES "catalog_category" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_merchantprofile_supp_merchantprofile_id_deab69be" ON "store_merchantprofile_supported_categories" ("merchantprofile_id");
CREATE INDEX "store_merchantprofile_supported_categories_category_id_b16b4dba" ON "store_merchantprofile_supported_categories" ("category_id");
ALTER TABLE "store_merchantprofile_payment_methods" ADD CONSTRAINT "store_merchantprofile_pa_merchantprofile_id_payme_a933f944_uniq" UNIQUE ("merchantprofile_id", "paymentmethod_id");
ALTER TABLE "store_merchantprofile_payment_methods" ADD CONSTRAINT "store_merchantprofil_merchantprofile_id_a70060c1_fk_store_mer" FOREIGN KEY ("merchantprofile_id") REFERENCES "store_merchantprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_merchantprofile_payment_methods" ADD CONSTRAINT "store_merchantprofil_paymentmethod_id_15d7c318_fk_store_pay" FOREIGN KEY ("paymentmethod_id") REFERENCES "store_paymentmethod" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_merchantprofile_paym_merchantprofile_id_a70060c1" ON "store_merchantprofile_payment_methods" ("merchantprofile_id");
CREATE INDEX "store_merchantprofile_payment_methods_paymentmethod_id_15d7c318" ON "store_merchantprofile_payment_methods" ("paymentmethod_id");
ALTER TABLE "store_merchantprofile_pickup_locations" ADD CONSTRAINT "store_merchantprofile_pi_merchantprofile_id_picku_da0ae0a3_uniq" UNIQUE ("merchantprofile_id", "pickuplocation_id");
ALTER TABLE "store_merchantprofile_pickup_locations" ADD CONSTRAINT "store_merchantprofil_merchantprofile_id_1ed511ee_fk_store_mer" FOREIGN KEY ("merchantprofile_id") REFERENCES "store_merchantprofile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "store_merchantprofile_pickup_locations" ADD CONSTRAINT "store_merchantprofil_pickuplocation_id_7ec816e1_fk_store_pic" FOREIGN KEY ("pickuplocation_id") REFERENCES "store_pickuplocation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_merchantprofile_pick_merchantprofile_id_1ed511ee" ON "store_merchantprofile_pickup_locations" ("merchantprofile_id");
CREATE INDEX "store_merchantprofile_pick_pickuplocation_id_7ec816e1" ON "store_merchantprofile_pickup_locations" ("pickuplocation_id");
ALTER TABLE "store_auditlog" ADD CONSTRAINT "store_auditlog_user_id_5d27358b_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_auditlog_user_id_5d27358b" ON "store_auditlog" ("user_id");
CREATE INDEX "store_audit_action_09eac6_idx" ON "store_auditlog" ("action", "created_at");
ALTER TABLE "store_notification" ADD CONSTRAINT "store_notification_recipient_id_9f52965b_fk_accounts_user_id" FOREIGN KEY ("recipient_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "store_notification_recipient_id_9f52965b" ON "store_notification" ("recipient_id");
CREATE INDEX "store_notif_recipie_7960ef_idx" ON "store_notification" ("recipient_id", "is_read");
--
-- Create model Order
--
CREATE TABLE "orders_order" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "number" varchar(20) NOT NULL UNIQUE, "contact_name" varchar(160) NOT NULL, "contact_email" varchar(254) NOT NULL, "contact_phone" varchar(40) NOT NULL, "status" varchar(24) NOT NULL, "delivery_snapshot" jsonb NOT NULL, "subtotal" numeric(12, 2) NOT NULL, "delivery_fee" numeric(10, 2) NOT NULL, "total" numeric(12, 2) NOT NULL, "currency" varchar(8) NOT NULL, "internal_notes" text NOT NULL, "stock_committed" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "customer_id" bigint NULL, "delivery_address_id" bigint NULL, "fulfilment_method_id" bigint NULL, "payment_method_id" bigint NULL, "pickup_location_id" bigint NULL);
--
-- Create model OrderItem
--
CREATE TABLE "orders_orderitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "product_name" varchar(200) NOT NULL, "sku" varchar(64) NOT NULL, "unit_price" numeric(12, 2) NOT NULL, "quantity" integer NOT NULL CHECK ("quantity" >= 0), "line_total" numeric(12, 2) NOT NULL, "order_id" bigint NOT NULL, "product_id" bigint NULL);
--
-- Create model OrderStatusEvent
--
CREATE TABLE "orders_orderstatusevent" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "from_status" varchar(24) NOT NULL, "to_status" varchar(24) NOT NULL, "note" varchar(255) NOT NULL, "created_at" timestamp with time zone NOT NULL, "changed_by_id" bigint NULL, "order_id" bigint NOT NULL);
--
-- Create model Payment
--
CREATE TABLE "orders_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "status" varchar(16) NOT NULL, "amount" numeric(12, 2) NOT NULL, "reference" varchar(120) NOT NULL, "verified_at" timestamp with time zone NULL, "rejection_reason" text NOT NULL, "updated_at" timestamp with time zone NOT NULL, "method_id" bigint NULL, "order_id" bigint NOT NULL UNIQUE, "verified_by_id" bigint NULL);
--
-- Create model PaymentProof
--
CREATE TABLE "orders_paymentproof" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "file" varchar(100) NOT NULL, "original_name" varchar(255) NOT NULL, "content_type" varchar(100) NOT NULL, "size_bytes" integer NOT NULL CHECK ("size_bytes" >= 0), "reference" varchar(120) NOT NULL, "uploaded_at" timestamp with time zone NOT NULL, "order_id" bigint NOT NULL, "payment_id" bigint NULL, "uploaded_by_id" bigint NULL);
--
-- Create index orders_orde_status_c6dd84_idx on field(s) status of model order
--
CREATE INDEX "orders_orde_status_c6dd84_idx" ON "orders_order" ("status");
--
-- Create index orders_orde_number_539d36_idx on field(s) number of model order
--
CREATE INDEX "orders_orde_number_539d36_idx" ON "orders_order" ("number");
--
-- Create index orders_orde_custome_413d7d_idx on field(s) customer, -created_at of model order
--
CREATE INDEX "orders_orde_custome_413d7d_idx" ON "orders_order" ("customer_id", "created_at" DESC);
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_customer_id_0b76f6a4_fk_accounts_user_id" FOREIGN KEY ("customer_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_delivery_address_id_6ecfdbf4_fk_accounts_" FOREIGN KEY ("delivery_address_id") REFERENCES "accounts_address" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_fulfilment_method_id_fd82c0da_fk_store_ful" FOREIGN KEY ("fulfilment_method_id") REFERENCES "store_fulfilmentmethod" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_payment_method_id_532d9073_fk_store_pay" FOREIGN KEY ("payment_method_id") REFERENCES "store_paymentmethod" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_order" ADD CONSTRAINT "orders_order_pickup_location_id_f50f729f_fk_store_pic" FOREIGN KEY ("pickup_location_id") REFERENCES "store_pickuplocation" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_order_number_abc9e0f2_like" ON "orders_order" ("number" varchar_pattern_ops);
CREATE INDEX "orders_order_customer_id_0b76f6a4" ON "orders_order" ("customer_id");
CREATE INDEX "orders_order_delivery_address_id_6ecfdbf4" ON "orders_order" ("delivery_address_id");
CREATE INDEX "orders_order_fulfilment_method_id_fd82c0da" ON "orders_order" ("fulfilment_method_id");
CREATE INDEX "orders_order_payment_method_id_532d9073" ON "orders_order" ("payment_method_id");
CREATE INDEX "orders_order_pickup_location_id_f50f729f" ON "orders_order" ("pickup_location_id");
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_order_id_fe61a34d_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderitem" ADD CONSTRAINT "orders_orderitem_product_id_afe4254a_fk_catalog_product_id" FOREIGN KEY ("product_id") REFERENCES "catalog_product" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_orderitem_order_id_fe61a34d" ON "orders_orderitem" ("order_id");
CREATE INDEX "orders_orderitem_product_id_afe4254a" ON "orders_orderitem" ("product_id");
ALTER TABLE "orders_orderstatusevent" ADD CONSTRAINT "orders_orderstatusev_changed_by_id_fea60226_fk_accounts_" FOREIGN KEY ("changed_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_orderstatusevent" ADD CONSTRAINT "orders_orderstatusevent_order_id_c81bad02_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_orderstatusevent_changed_by_id_fea60226" ON "orders_orderstatusevent" ("changed_by_id");
CREATE INDEX "orders_orderstatusevent_order_id_c81bad02" ON "orders_orderstatusevent" ("order_id");
ALTER TABLE "orders_payment" ADD CONSTRAINT "orders_payment_method_id_ed820f74_fk_store_paymentmethod_id" FOREIGN KEY ("method_id") REFERENCES "store_paymentmethod" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_payment" ADD CONSTRAINT "orders_payment_order_id_bdccf250_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_payment" ADD CONSTRAINT "orders_payment_verified_by_id_f70e064d_fk_accounts_user_id" FOREIGN KEY ("verified_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_payment_method_id_ed820f74" ON "orders_payment" ("method_id");
CREATE INDEX "orders_payment_verified_by_id_f70e064d" ON "orders_payment" ("verified_by_id");
ALTER TABLE "orders_paymentproof" ADD CONSTRAINT "orders_paymentproof_order_id_3ba44f78_fk_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "orders_order" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_paymentproof" ADD CONSTRAINT "orders_paymentproof_payment_id_20023e81_fk_orders_payment_id" FOREIGN KEY ("payment_id") REFERENCES "orders_payment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders_paymentproof" ADD CONSTRAINT "orders_paymentproof_uploaded_by_id_7aa1383d_fk_accounts_user_id" FOREIGN KEY ("uploaded_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "orders_paymentproof_order_id_3ba44f78" ON "orders_paymentproof" ("order_id");
CREATE INDEX "orders_paymentproof_payment_id_20023e81" ON "orders_paymentproof" ("payment_id");
CREATE INDEX "orders_paymentproof_uploaded_by_id_7aa1383d" ON "orders_paymentproof" ("uploaded_by_id");
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");

COMMIT;
