# Generated by Django 5.1.4 on 2026-10-03 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FulfilmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_areas', models.TextField(blank=True, help_text='Comma or newline separated serviceable areas.')),
                ('instructions', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports {order_number}, {customer_name}, {status}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, help_text='Shown to the customer after order submission.')),
                ('account_name', models.CharField(blank=True, max_length=160)),
                ('account_number', models.CharField(blank=True, max_length=120)),
                ('reference_hint', models.CharField(blank=True, help_text="e.g. 'Use your order number as the reference.'", max_length=200)),
                ('requires_proof', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('hours', models.CharField(blank=True, max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('group', models.CharField(default='store', max_length=40)),
                ('label', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'created_at'], name='store_analy_name_1f43a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('license_info', models.TextField(blank=True)),
                ('operating_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fulfilment_methods', models.ManyToManyField(blank=True, to='store.fulfilmentmethod')),
                ('supported_categories', models.ManyToManyField(blank=True, related_name='merchants', to='catalog.category')),
                ('payment_methods', models.ManyToManyField(blank=True, to='store.paymentmethod')),
                ('pickup_locations', models.ManyToManyField(blank=True, to='store.pickuplocation')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(blank=True, max_length=80)),
                ('object_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='store_audit_action_09eac6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order_number', models.CharField(blank=True, max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('provider', models.CharField(default='console', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='store_notif_recipie_7960ef_idx')],
            },
        ),
    ]
